CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_username ON users (username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);

CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    age INT,
    course VARCHAR(120),
    user_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_students_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_students_email ON students (email);
CREATE INDEX IF NOT EXISTS idx_students_course ON students (course);

CREATE TABLE IF NOT EXISTS teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    department VARCHAR(120) NOT NULL,
    specialization VARCHAR(120),
    qualification VARCHAR(120),
    user_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_teachers_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_teachers_email ON teachers (email);
CREATE INDEX IF NOT EXISTS idx_teachers_department ON teachers (department);

CREATE TABLE IF NOT EXISTS login_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    role VARCHAR(30) NOT NULL,
    login_time TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_login_logs_username ON login_logs (username);
CREATE INDEX IF NOT EXISTS idx_login_logs_role ON login_logs (role);
CREATE INDEX IF NOT EXISTS idx_login_logs_login_time ON login_logs (login_time);

CREATE TABLE IF NOT EXISTS subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    course VARCHAR(120) NOT NULL,
    semester VARCHAR(30),
    teacher_id BIGINT,
    CONSTRAINT fk_subjects_teacher FOREIGN KEY (teacher_id) REFERENCES teachers (id)
);

CREATE INDEX IF NOT EXISTS idx_subjects_code ON subjects (code);
CREATE INDEX IF NOT EXISTS idx_subjects_course ON subjects (course);

CREATE TABLE IF NOT EXISTS enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    CONSTRAINT uk_enrollments_student_subject UNIQUE (student_id, subject_id),
    CONSTRAINT fk_enrollments_student FOREIGN KEY (student_id) REFERENCES students (id),
    CONSTRAINT fk_enrollments_subject FOREIGN KEY (subject_id) REFERENCES subjects (id)
);

CREATE INDEX IF NOT EXISTS idx_enrollments_student ON enrollments (student_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_subject ON enrollments (subject_id);

CREATE TABLE IF NOT EXISTS attendance_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    class_date DATE NOT NULL,
    topic VARCHAR(180),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_attendance_sessions_subject FOREIGN KEY (subject_id) REFERENCES subjects (id),
    CONSTRAINT fk_attendance_sessions_teacher FOREIGN KEY (teacher_id) REFERENCES teachers (id)
);

CREATE INDEX IF NOT EXISTS idx_attendance_sessions_teacher ON attendance_sessions (teacher_id);
CREATE INDEX IF NOT EXISTS idx_attendance_sessions_subject_date ON attendance_sessions (subject_id, class_date);

CREATE TABLE IF NOT EXISTS attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    remarks VARCHAR(180),
    CONSTRAINT uk_attendance_records_session_student UNIQUE (session_id, student_id),
    CONSTRAINT fk_attendance_records_session FOREIGN KEY (session_id) REFERENCES attendance_sessions (id),
    CONSTRAINT fk_attendance_records_student FOREIGN KEY (student_id) REFERENCES students (id)
);

CREATE INDEX IF NOT EXISTS idx_attendance_records_student ON attendance_records (student_id);
CREATE INDEX IF NOT EXISTS idx_attendance_records_status ON attendance_records (status);

CREATE TABLE IF NOT EXISTS study_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    title VARCHAR(140) NOT NULL,
    description VARCHAR(240),
    content CLOB NOT NULL,
    attachment_url VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_study_notes_subject FOREIGN KEY (subject_id) REFERENCES subjects (id),
    CONSTRAINT fk_study_notes_teacher FOREIGN KEY (teacher_id) REFERENCES teachers (id)
);

CREATE INDEX IF NOT EXISTS idx_study_notes_teacher ON study_notes (teacher_id);
CREATE INDEX IF NOT EXISTS idx_study_notes_subject ON study_notes (subject_id);
CREATE INDEX IF NOT EXISTS idx_study_notes_created_at ON study_notes (created_at);
